[package]
name = "report"
version = "0.1.0"
edition = "2024"

[[bin]]
name="report"
path="src/main.rs"

[dependencies]
lib = {path="../lib"}
plotters = {version="0.3.7"}
clap = { version = "4", features = ["derive"] }
